spring.application.name=config-server
server.port=8888
spring.profiles.active=native
spring.cloud.config.server.bootstrap=true
spring.cloud.config.server.native.search-locations=file:///app/properties,classpath:/
spring.cloud.config.server.git.search-paths={application}
# Actuator properties
management.endpoints.web.base-path=/health/${spring.application.name}
management.endpoints.web.path-mapping.health=status
management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.access=UNRESTRICTED
spring.docker.compose.enabled=false