spring.application.name=config-server
server.port=8888
spring.profiles.active=native
spring.cloud.config.server.bootstrap=true
spring.cloud.config.server.native.search-locations=file:///app/properties,classpath:/
# Actuator properties
management.endpoints.web.base-path=/health/${spring.application.name}
management.endpoints.web.path-mapping.health=status
management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.access=UNRESTRICTED
spring.docker.compose.enabled=false
# devtools properties
spring.devtools.livereload.port=35729
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**,templates/**,META-INF/**,resources/**,application-*.properties